const Action = {
	ADD_GROUP: 'ADD_GROUP',
	REMOVE_GROUP: 'REMOVE_GROUP',
	ADD_ITEM: 'ADD_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	// EDIT_ITEM: 'EDIT_ITEM',
	PROCRASTINATE: 'PROCRASTINATE',
	MARK_AS_DONE: 'MARK_AS_DONE',
	MARK_AS_UNDONE: 'MARK_AS_UNDONE',
}

export default Action
